name: hot_take_mobile
description: Hot Take Flutter mobile app
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  socket_io_client: ^2.0.3+1
  flutter:
    sdk: flutter
  http: ^1.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/leinecker.png

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
